import Dummy_Profile from '../../media/dummy_profile.jpg';

const  dummy_posts =[

        {
            age_group: "27",
            country: "India",
            description: "He is not found.. yet..",
            disability: "not_disabled",
            dp_image: "/static/media/dummy_profile.1f7abd55.jpg",
            follwed_by: [],
            gender: "male",
            location: "Andheri",
            name: "Ghulam Raza",
            notification_id: 786000,
            post_creator_email: "assdf@gmail.com",
            post_creator_name: "Sultan",
            post_id: 789177930000,
            post_status: "active",
            post_time: {date: 28, month: 6, year: 2020},
            region: "Delhi",
            status: "missing",
        },
        {
            age_group: "23",
            country: "Pakistan",
            description: "He is not missed.. yet..",
            disability: "not_disabled",
            dp_image: "/static/media/dummy_profile.1f7abd55.jpg",
            follwed_by: [],
            gender: "female",
            location: "Ghulshan Iqbal",
            name: "Maruti",
            notification_id: 786001,
            post_creator_email: "asdf@gmail.com",
            post_creator_name: "Sultan",
            post_id: 789177930001,
            post_status: "active",
            post_time: {date: 28, month: 6, year: 2020},
            region: "Punjab",
            status: "found",
        },
        // {
        //     age_group: "27",
        //     country: "Pakistan",
        //     description: "He is not missed.. yet..",
        //     disability: "not_disabled",
        //     dp_image: "/static/media/dummy_profile.1f7abd55.jpg",
        //     follwed_by: [],
        //     gender: "female",
        //     location: "Sar-gojra, Chakwal",
        //     name: "Gulsim",
        //     notification_id: 786002,
        //     post_creator_email: "asddf@gmail.com",
        //     post_creator_name: "Naeem",
        //     post_id: 789177930002,
        //     post_status: "active",
        //     post_time: {date: 28, month: 6, year: 2020},
        //     region: "Punjab",
        //     status: "missing",
        // },
        // {
        //     age_group: "33",
        //     country: "Pakistan",
        //     description: "He is not missed.. yet..",
        //     disability: "not_disabled",
        //     dp_image: "/static/media/dummy_profile.1f7abd55.jpg",
        //     follwed_by: [],
        //     gender: "male",
        //     location: "12 - Block SGD",
        //     name: "Dogar",
        //     notification_id: 786003,
        //     post_creator_email: "asfdf@gmail.com",
        //     post_creator_name: "Hamza",
        //     post_id: 789177930003,
        //     post_status: "active",
        //     post_time: {date: 28, month: 6, year: 2020},
        //     region: "Punjab",
        //     status: "found",
        // },
]


export default dummy_posts;